Algoritmo "antecessor"
// Disciplina  : [Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Ler o valor e mostrar o antecessor! (função)
// Autor(a)    : Caroline Mota
// Data atual  : 18/09/2025
Var
// Seção de Declarações das variáveis 
numero: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval ("Digite um número:")
leia (numero)

Escreval("Resultado:", numero -1)

Fimalgoritmo